trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: Kubernetes@1
  displayName: 'Deploy to Development'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 
    command: 'apply'
    arguments: '-f dev.yaml'
    namespace: jesse
